# Generated by Django 2.2.24 on 2021-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210607_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
