# Generated by Django 2.2.24 on 2021-06-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_commentforproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentforproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.Product', verbose_name='Товар'),
        ),
    ]
